### ISSUE TITLE
only one GPU

### ISSUE THREAD

**Issue by xiaoweihappy123** [JDAI-CV/Partial-Person-ReID#1]
Hello, I changed part of the code because there was only one GPU, but what does this error mean?
I haven't seen it before.Could you give me some advice.
        
Thanks.

Ep 400, 63.31s, prec 99.97%, sm 98.60%, d_ap 1.4526, d_an 2.8813, loss 0.0024
Extracting feature...
1000/1000 batches done, +5.16s, total 242.56s
Done, 620.85s
(2048, 71)
Computing distance...
0/15913 batches done
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1513363039688/work/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu line=343 error=8 : invalid device function
Traceback (most recent call last):
  File "script/experiment/train.py", line 542, in <module>
    main()
  File "script/experiment/train.py", line 538, in main
    test(load_model_weight=False)
  File "script/experiment/train.py", line 405, in test
    verbose=True)
  File "./tri_loss/dataset/TestSet.py", line 190, in eval
    q_g_spatial_dist = dsr_dist(spatial_feat[q_inds], spatial_feat[g_inds])
  File "./tri_loss/utils/distance.py", line 73, in dsr_dist
    a = torch.matmul(y, torch.matmul(Proj_M, temp)) - temp
  File "/home/xiaowei/anaconda2/lib/python2.7/site-packages/torch/tensor.py", line 300, in __sub__
    return self.sub(other)
RuntimeError: cuda runtime error (8) : invalid device function at /opt/conda/conda-bld/pytorch_1513363039688/work/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:343
[2]+  已杀死               python script/experiment/train.py --dataset market1501 --partial_dataset holistic --spatial_train False --total_epochs 400 --ids_per_batch 8

**Comment by xiaoweihappy123** [comment]
I have solved this problem through the following link, hope that someone can take less detours.


https://github.com/pytorch/pytorch/issues/686
